### PR TITLE
Allow internal anchors

### PR DESCRIPTION
**Pull request by mattia8961**
Add condition to "updateUrl" method

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Allow internal anchors, so not add `http://` before a URL that starts with `#`
| Type?         |  improvement
| BC breaks?    | no
| Deprecations? | no
| How to test?  |- Create or edit a slide<br>- Insert internal anchor in the URL filed (i.e. "#internal-anchor")<br>- Save the slide<br>- Create a `div` element or any other HTML element and add the id property (i.e. `id="internal-anchor"` in the footer)<br>- Click on the slide, should point to a section of the page with that id, not to `about:blank#blocked`.

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by sarahdib** [comment]
Hello @mattia8961 

There is a bug when I try to configure the module 
Capture d’écran 2021-07-19 à 19 39 47


Could you check ?
Thank you

**Comment by tups** [comment]
Hello,

I think we can go further. What is the point of this function?
It creates more problem than it fixes and it doesn't protect URLs anyway, they break them.

It breaks the links that are added without a domain name.

For example :
- `/cart` devient `http:///cart`
- `#mon-id` becomes `http://#mon-id`
- Universal URL : `//github.com` becomes `http:////github.com`
- Or if we make a mistake : `htp://github.com` becomes `http://htp://github.com`

Why not take it off?

What do you think @PierreRambaud ?

**Comment by mattia8961** [comment]
Hello @sarahdib,

I don't have this issue, how can I reproduce it?

I tried to unistall the module and reinstalling it having no errors, even activating the debug mode

**Comment by PierreRambaud** [comment]
@sarahdib Shouldn't be related to this pull request, could you please retry without this PR and a dedicated release and not the develop branch?

@tups I don't understand, I'm also not able to reproduce what you said :thinking: 

> For example:
> - `about` becomes `http://prestashop.com\path\about`
> - `/about` becomes `http://prestashop.com\about`
> - `#my-id` becomes `http://prestashop.com\path\#my-id` with no need to reload the page, and no need to make an exception to  allow that
> - `//prestashop.com` becomes `http://prestashop.com`

It's the right way to manage URLs IMHO :)

**Comment by tups** [comment]
> 
> @tups I don't understand, I'm also not able to reproduce what you said 🤔
> 

Just try this when you create a new slide:
image

On the template, we get:
image

While the site is in HTTPS first, and this change of URL does not make sense from an administration

> For example :
> 
>     * `/cart` devient `http:///cart`
> 
>     * `#mon-id` becomes `http://#mon-id`
> 
>     * Universal URL : `//github.com` becomes `http:////github.com`
> 
>     * Or if we make a mistake : `htp://github.com` becomes `http://htp://github.com`
>

**Comment by PierreRambaud** [comment]
> > @tups I don't understand, I'm also not able to reproduce what you said thinking
> 
> Just try this when you create a new slide:
> image
> 
> On the template, we get:
> image
> 
> While the site is in HTTPS first, and this change of URL does not make sense from an administration
> 
> > For example :
> > ```
> > * `/cart` devient `http:///cart`
> > 
> > * `#mon-id` becomes `http://#mon-id`
> > 
> > * Universal URL : `//github.com` becomes `http:////github.com`
> > 
> > * Or if we make a mistake : `htp://github.com` becomes `http://htp://github.com`
> > ```

This is another problem, not related to this PR. We can accept this one first, then find a better way to handle all use cases

**Comment by tups** [comment]
I let @ mattia8961 finalize. I'll do a PR for the url bug.

**Comment by mattia8961** [comment]
Ok, I close this PR, since the solution for me and @tups is to remove the `updateUrl` method that creates more problems than it solves.
So I leave to @tups  to create a new PR for this topic.

**Pull request closed without merging**
