### PR TITLE
shorten trans call

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Module class has its own [trans](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/module/Module.php#L3363) function so we need to replace `getTranslator()->trans` by `trans` to keep consistency and briefness.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/PrestaShop#30193
| How to test?  | Nothing changes in module's behaviour. Check the Module `trans` code in the above Description is the best way verify that this PR is correct.

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
calling the `trans` method from `Module.php` does not behave exactly like calling it from the translator itself...

Here the difference is that now the `htmlspecialchars` function will be applied to all translations with `ENT_NOQUOTES` parameter.

It shouldn't be a problem but I think it should be QA-validated since the behavior is changing. 

LGTM otherwise :+1:

**Comment by leemyongpakvn** [comment]
@matthieu-rolland I still think this module behavior is not changing because we don't have any special character in trans strings here.

**Comment by paulnoelcholot** [comment]
Hello @leemyongpakvn ,

Thanks for your PR. The issue is welle fixed and I found no regression :tada:

**Review by paulnoelcholot — APPROVED** [review]

**Comment by kpodemski** [comment]
Thank you @leemyongpakvn

**Pull request merged**
