### PR TITLE
Removed required property from URL

### PR DESCRIPTION
**Pull request by gabrielobleite**
Removed required property from URL but kept the others URL restrictions.

Fixes PrestaShop/PrestaShop#18536

### CODE REVIEW

**Comment by jf-viguier** [comment]
Thanks @gabrielobleite

**Comment by sarahdib** [comment]
Hello @gabrielobleite 

Thank you for this contribution.
I found a bug with this pr I configure a slide without url and when I went to the front office and click and this slide the link redirect to a blank page : about:blank#blocked 

https://drive.google.com/file/d/1g8H_OQCwNe1Knx2-qlX4bGdXGPuglUqx/view

**Comment by DevPrestaTooEasy** [comment]
Hello

I think this bug come from line 656 : `$slide['url'] = $this->updateUrl($slide['url']);` because this function try to add http:// to the link
Remove this function resolve both empty link and relative link

I suggest to modify the tpl to change `<a href="{$slide.url}">` to `<a {if $slide.url != ''}href="{$slide.url}"{/if}>` for disable click

I hope i doing this right for my first contribution

Best Regards

**Comment by PierreRambaud** [comment]
Hi @gabrielobleite ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
