### PR TITLE
Release 3.1.1

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 3.1.1
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Release Test

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Progi1984 ,

Tested on 1.7.8.x and develop branch.
- CRUD ok
- anchor links work well
- checked BO and FO display
- configure settings and slides list

There's 2 remaining issues :
I have a warning when I try to add a new slider 🚫 
Screenshot 2022-04-13 at 10 48 11

The length of the field in the configuration form is not ok, it should be the same length as all other fields.
on develop branch 🚫 
Screenshot 2022-04-13 at 10 57 15
on 1.7.8.X branch ✅ 
Screenshot 2022-04-13 at 11 04 01
responsive is OK

Could you check ?
Thanks!

**Comment by Progi1984** [comment]
@florine2623 The PR for fixing these bugs : #73.

**Comment by Progi1984** [comment]
@florine2623 Congratulations :tada: You unlock the release :)

**Review by NeOMakinG — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

The previous bug has been fixed ! It is looking good to me on develop and 1.7.8.x.
QA ✅

**Comment by Progi1984** [comment]
Thanks @florine2623

**Pull request merged**
