### PR TITLE
Release 3.2.1

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release 3.2.1
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

### CODE REVIEW

**Review by ShaiMagal — APPROVED** [review]

**Comment by ShaiMagal** [comment]
Merging as it was tested here https://github.com/PrestaShop/ps_imageslider/pull/110 and there was only one change.

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Comment by kpodemski** [comment]
hello @ShaiMagal 

it's QA decision to make, not yours

**Comment by Hlavtox** [comment]
@kpodemski I discussed this with @florine2623 and she tested the PR few hours ago.

**Comment by Hlavtox** [comment]
I asked Dominik to merge it so we can deliver the fix quickly.

**Comment by Hlavtox** [comment]
@kpodemski 
- I did the last PR https://github.com/PrestaShop/ps_imageslider/pull/96 and missed an issue that somebody else made.
- I released [3.2.0](https://github.com/PrestaShop/ps_imageslider/pull/107)
- I fixed it [here](https://github.com/PrestaShop/ps_imageslider/pull/110) and florine properly tested it. Including upgrade. Also, Dominik [tested it](https://github.com/PrestaShop/ps_imageslider/pull/110#issuecomment-2374375939). Also the person who reported the issue [tested it](https://github.com/PrestaShop/PrestaShop/issues/37027#issuecomment-2374395262). Works fine.
- I made this release PR with the ONLY ONE change and I asked Dominik to merge it, so we can deliver the fix.

Am I wrong here?

**Comment by kpodemski** [comment]
Hi @Hlavtox 

In that case it's all clear, it should be written in the merge message or @florine2623 could put QA Approved label

**Comment by Hlavtox** [comment]
@kpodemski OK, I will make sure to note it for the police next time 🤣

**Pull request merged**
