### PR TITLE
Release 3.1.3

### PR DESCRIPTION
**Pull request by JoseNOM**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 3.1.3
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Release 3.1.3 works as expected

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by JoseNOM** [comment]
Great thanks @kpodemski

**Review by florine2623 — APPROVED** [review]
Hello @JoseNOM ,

Tested the release. Bump to vers 3.1.3 is OK and issue https://github.com/PrestaShop/ps_imageslider/pull/84 is fixed.

It is QA ✅

**Comment by nicosomb** [comment]
Thank you @JoseNOM

**Comment by JoseNOM** [comment]
Thank you! Can you create the git tag? I need it

**Comment by nicosomb** [comment]
https://github.com/PrestaShop/ps_imageslider/releases/tag/v3.1.3

**Pull request merged**
