### PR TITLE
Replace oudated jqueryuiSortable by modern SortableJS

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  |  Please check the Fixed ticket below.<br> _(I already made a similar PR for blockreassurance module. **NeOMakinG** suggested adding SortableJS to the Core js  there to use as a common library, but waiting to the next major version is indefinite so I chose using SortableJS as the module's local lib here)_
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/30210. Related to [Issue 27186](https://github.com/PrestaShop/PrestaShop/issues/27186) (partialy)
| How to test?  | 1. Apply this PR changes <br> 2. Clear Web browser cache and PrestaShop BO cache <br> 3. Check sortable feature in the module BO Config's Slides list to make sure the item can be dragged, dropped and saved there, then showed in FO accordingly, as usual.

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
🍭

**Review by SharakPL — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @leemyongpakvn ,

I have checked your PR and it is QA approved :heavy_check_mark: 

Thank you!

**Comment by kpodemski** [comment]
Well done @leemyongpakvn 👏 thank you

**Comment by leemyongpakvn** [comment]
Great @kpodemski :fireworks: . I think we need to complete the related ongoing PR with blockreassurance before closing [issue 30210](PrestaShop/PrestaShop/issues/30210).

**Pull request merged**
